### ISSUE TITLE
It appears the `nested_workflow.png` image in `1_intro_pydra.ipynb` is still missing. Couldn't find it in `figures/`..

### ISSUE THREAD

**Issue by effigies** [nipype/pydra-tutorial#11]
It appears the `nested_workflow.png` image in `1_intro_pydra.ipynb` is still missing. Couldn't find it in `figures/`..

![image](https://user-images.githubusercontent.com/30598330/108221214-89773c00-7105-11eb-972e-cbd00712c635.png)

_Originally posted by @SamGuay in https://github.com/nipype/pydra-tutorial/issues/3#issuecomment-780652615_

**Comment by effigies** [comment]
Creating a new issue, since the original file is now gone. We either need to re-add it or rename it to whatever replaced it.

**Comment by SamGuay** [comment]
I was about to open a new issue, then look for the file name and saw it had been mentioned in #3 :sweat_smile:. Thanks, I will know I can open a new issue next time!

**Comment by djarecka** [comment]
@SamGuay - thanks, forgot to add the file to git. and feel free to open new issues next time :)
