### ISSUE TITLE
Figures are missing, or have wrong outputs

### ISSUE THREAD

**Issue by hjmjohnson** [nipype/pydra-tutorial#3]
../figures/nested_workflow.png

Both images have wrong outputs associated with inputs provided

![image](https://user-images.githubusercontent.com/313970/84571940-57cef980-ad5c-11ea-826c-7d61824da5c5.png)

![image](https://user-images.githubusercontent.com/313970/84571943-60bfcb00-ad5c-11ea-98dd-497e34d0e87f.png)

**Comment by djarecka** [comment]
you're right, thank you pointing this!

**Comment by SamGuay** [comment]
It appears the `nested_workflow.png` image in `1_intro_pydra.ipynb` is still missing. Couldn't find it in `figures/`..

![image](https://user-images.githubusercontent.com/30598330/108221214-89773c00-7105-11eb-972e-cbd00712c635.png)
