### ISSUE TITLE
7_twolevel_glm_nilearn doesn't work well on jupyterbook

### ISSUE THREAD

**Issue by yibeichan** [nipype/pydra-tutorial#37]
It seems that we have some problems of running this tutorial on jupyerbook. I suspect that it's related to `datalad` again. We probably need to provide fake username and email for it. I'll fix it soon.

**Comment by yibeichan** [comment]
@djarecka It sems that I can't add labels to this issue or assign myself.

**Comment by djarecka** [comment]
I gave you permission, so you should be able to add yourself next time

**Comment by yibeichan** [comment]
@djarecka yes yes yes, the fake git username and email worked! I'm closing this issue now.
