### ISSUE TITLE
Typo in Workflow section 4.2 (Workflow as a node)

### ISSUE THREAD

**Issue by adi611** [nipype/pydra-tutorial#44]
In the code block provided for section 4.2 of Workflow there is a minor typo error in the comment:
```
# connecting wfa to the input from the main workflow
wf2a.inputs.x = wf5.lzin.x
```
`wf2a` is incorrectly written as `wfa`

**Comment by djarecka** [comment]
thanks, could you please create a PR

**Comment by adi611** [comment]
Sure, I have created a PR for this.
